language: go
go:
- 1.15.x
script: go build /home/travis/gopath/src/github.com/ajtechdeveloper/grpc-go-mongodb-cobra/server /home/travis/gopath/src/github.com/ajtechdeveloper/grpc-go-mongodb-cobra/client /home/travis/gopath/src/github.com/ajtechdeveloper/grpc-go-mongodb-cobra/client/cmd